// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWxe0lFzlp2t502rlQj_MvQZcuHgA6eM',
    appId: '1:171205090830:web:497c9bce5c5afce13a665f',
    messagingSenderId: '171205090830',
    projectId: 'bookswap-app-72016',
    authDomain: 'bookswap-app-72016.firebaseapp.com',
    storageBucket: 'bookswap-app-72016.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NN0UGj55ySxgIAOzlcvhpnuYkznineo',
    appId: '1:171205090830:android:1792479a52296eb13a665f',
    messagingSenderId: '171205090830',
    projectId: 'bookswap-app-72016',
    storageBucket: 'bookswap-app-72016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSC456o_CRIQVzZ4ds2WHGYP1NJaJ-Fg',
    appId: '1:171205090830:ios:5e1ec5c5d1d48de53a665f',
    messagingSenderId: '171205090830',
    projectId: 'bookswap-app-72016',
    storageBucket: 'bookswap-app-72016.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSC456o_CRIQVzZ4ds2WHGYP1NJaJ-Fg',
    appId: '1:171205090830:ios:5e1ec5c5d1d48de53a665f',
    messagingSenderId: '171205090830',
    projectId: 'bookswap-app-72016',
    storageBucket: 'bookswap-app-72016.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXWxe0lFzlp2t502rlQj_MvQZcuHgA6eM',
    appId: '1:171205090830:web:2f77d8f6a4b27aea3a665f',
    messagingSenderId: '171205090830',
    projectId: 'bookswap-app-72016',
    authDomain: 'bookswap-app-72016.firebaseapp.com',
    storageBucket: 'bookswap-app-72016.firebasestorage.app',
  );
}
