// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmTzzRDD_fqEgzDowtHRKBfLhPml5qh8',
    appId: '1:560423501156:web:351075215c36d537274e71',
    messagingSenderId: '560423501156',
    projectId: 'bookswap-55e98',
    authDomain: 'bookswap-55e98.firebaseapp.com',
    storageBucket: 'bookswap-55e98.firebasestorage.app',
    measurementId: 'G-1WQ1GXB2T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQV7JgYbsNSrC801CBI0XhTQekXokEC8',
    appId: '1:560423501156:android:336932258d8f8265274e71',
    messagingSenderId: '560423501156',
    projectId: 'bookswap-55e98',
    storageBucket: 'bookswap-55e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvXBL6BVHIsiCkaYOM5tX9CGrKn-MW_-c',
    appId: '1:560423501156:ios:629ba543deb4ede5274e71',
    messagingSenderId: '560423501156',
    projectId: 'bookswap-55e98',
    storageBucket: 'bookswap-55e98.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSC456o_CRIQVzZ4ds2WHGYP1NJaJ-Fg',
    appId: '1:171205090830:ios:5e1ec5c5d1d48de53a665f',
    messagingSenderId: '171205090830',
    projectId: 'bookswap-app-72016',
    storageBucket: 'bookswap-app-72016.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTmTzzRDD_fqEgzDowtHRKBfLhPml5qh8',
    appId: '1:560423501156:web:e82a095c56bb5d8a274e71',
    messagingSenderId: '560423501156',
    projectId: 'bookswap-55e98',
    authDomain: 'bookswap-55e98.firebaseapp.com',
    storageBucket: 'bookswap-55e98.firebasestorage.app',
    measurementId: 'G-TRGCHWV9VP',
  );

}